
[relic_triggerbot]
	relic_place_triggerbot = true
	relic_pickup_triggerbot = true

[boss_waypoints]

	[boss_waypoints.general]
		line_starting_point = 1
		toggle = true
		ee2_jump_line = true
		jump_rings = true

	[boss_waypoints.color]
		show_through_blocks = true
		waypoint_color = "255,144,224,239"
		jump_ring_color = "255,0,255,0"

[auto_swap]

	[auto_swap.general]
		storm_lb_swap = true
		main_toggle = true

	[auto_swap.swaps]
		storm_swap = "volcano"
		maxor_swap = "adaptive"
		necron_swap = "adaptive"

[auto_clicker]

	[auto_clicker.left_click]
		min_cps = 18
		left_click = true
		max_cps = 20

	[auto_clicker.right_click]
		no_block = true
		min_cps = 13
		right_click = true
		max_cps = 15
		hold_confirmation_time = 146

[trap]
	waypoint_color = "255,255,170,0"
	tac_trap_waypoint = true
	x_offset = 2
	z_offset = 0

[tact_insert_cooldown]
	tactical_insertion_cooldown_timer = true

[secret_spawn_timer]
	solo_only = false
	secret_spawn_timer = true

